export interface Country {
  code: string;
  name: string;
  brokerGroup: 'A' | 'B' | 'US';
}

export const countries: Country[] = [
  // Group B Countries (UK + Australia)
  { code: 'GB', name: 'United Kingdom', brokerGroup: 'B' },
  { code: 'AU', name: 'Australia', brokerGroup: 'B' },
  
  // United States (Future)
  { code: 'US', name: 'United States', brokerGroup: 'US' },
  
  // Group A Countries (Rest of the world)
  { code: 'AD', name: 'Andorra', brokerGroup: 'A' },
  { code: 'AE', name: 'United Arab Emirates', brokerGroup: 'A' },
  { code: 'AF', name: 'Afghanistan', brokerGroup: 'A' },
  { code: 'AG', name: 'Antigua and Barbuda', brokerGroup: 'A' },
  { code: 'AI', name: 'Anguilla', brokerGroup: 'A' },
  { code: 'AL', name: 'Albania', brokerGroup: 'A' },
  { code: 'AM', name: 'Armenia', brokerGroup: 'A' },
  { code: 'AO', name: 'Angola', brokerGroup: 'A' },
  { code: 'AQ', name: 'Antarctica', brokerGroup: 'A' },
  { code: 'AR', name: 'Argentina', brokerGroup: 'A' },
  { code: 'AS', name: 'American Samoa', brokerGroup: 'A' },
  { code: 'AT', name: 'Austria', brokerGroup: 'A' },
  { code: 'AW', name: 'Aruba', brokerGroup: 'A' },
  { code: 'AX', name: 'Åland Islands', brokerGroup: 'A' },
  { code: 'AZ', name: 'Azerbaijan', brokerGroup: 'A' },
  { code: 'BA', name: 'Bosnia and Herzegovina', brokerGroup: 'A' },
  { code: 'BB', name: 'Barbados', brokerGroup: 'A' },
  { code: 'BD', name: 'Bangladesh', brokerGroup: 'A' },
  { code: 'BE', name: 'Belgium', brokerGroup: 'A' },
  { code: 'BF', name: 'Burkina Faso', brokerGroup: 'A' },
  { code: 'BG', name: 'Bulgaria', brokerGroup: 'A' },
  { code: 'BH', name: 'Bahrain', brokerGroup: 'A' },
  { code: 'BI', name: 'Burundi', brokerGroup: 'A' },
  { code: 'BJ', name: 'Benin', brokerGroup: 'A' },
  { code: 'BL', name: 'Saint Barthélemy', brokerGroup: 'A' },
  { code: 'BM', name: 'Bermuda', brokerGroup: 'A' },
  { code: 'BN', name: 'Brunei Darussalam', brokerGroup: 'A' },
  { code: 'BO', name: 'Bolivia', brokerGroup: 'A' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', brokerGroup: 'A' },
  { code: 'BR', name: 'Brazil', brokerGroup: 'A' },
  { code: 'BS', name: 'Bahamas', brokerGroup: 'A' },
  { code: 'BT', name: 'Bhutan', brokerGroup: 'A' },
  { code: 'BV', name: 'Bouvet Island', brokerGroup: 'A' },
  { code: 'BW', name: 'Botswana', brokerGroup: 'A' },
  { code: 'BY', name: 'Belarus', brokerGroup: 'A' },
  { code: 'BZ', name: 'Belize', brokerGroup: 'A' },
  { code: 'CA', name: 'Canada', brokerGroup: 'A' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', brokerGroup: 'A' },
  { code: 'CD', name: 'Congo, Democratic Republic of the', brokerGroup: 'A' },
  { code: 'CF', name: 'Central African Republic', brokerGroup: 'A' },
  { code: 'CG', name: 'Congo', brokerGroup: 'A' },
  { code: 'CH', name: 'Switzerland', brokerGroup: 'A' },
  { code: 'CI', name: "Côte d'Ivoire", brokerGroup: 'A' },
  { code: 'CK', name: 'Cook Islands', brokerGroup: 'A' },
  { code: 'CL', name: 'Chile', brokerGroup: 'A' },
  { code: 'CM', name: 'Cameroon', brokerGroup: 'A' },
  { code: 'CN', name: 'China', brokerGroup: 'A' },
  { code: 'CO', name: 'Colombia', brokerGroup: 'A' },
  { code: 'CR', name: 'Costa Rica', brokerGroup: 'A' },
  { code: 'CU', name: 'Cuba', brokerGroup: 'A' },
  { code: 'CV', name: 'Cabo Verde', brokerGroup: 'A' },
  { code: 'CW', name: 'Curaçao', brokerGroup: 'A' },
  { code: 'CX', name: 'Christmas Island', brokerGroup: 'A' },
  { code: 'CY', name: 'Cyprus', brokerGroup: 'A' },
  { code: 'CZ', name: 'Czechia', brokerGroup: 'A' },
  { code: 'DE', name: 'Germany', brokerGroup: 'A' },
  { code: 'DJ', name: 'Djibouti', brokerGroup: 'A' },
  { code: 'DK', name: 'Denmark', brokerGroup: 'A' },
  { code: 'DM', name: 'Dominica', brokerGroup: 'A' },
  { code: 'DO', name: 'Dominican Republic', brokerGroup: 'A' },
  { code: 'DZ', name: 'Algeria', brokerGroup: 'A' },
  { code: 'EC', name: 'Ecuador', brokerGroup: 'A' },
  { code: 'EE', name: 'Estonia', brokerGroup: 'A' },
  { code: 'EG', name: 'Egypt', brokerGroup: 'A' },
  { code: 'EH', name: 'Western Sahara', brokerGroup: 'A' },
  { code: 'ER', name: 'Eritrea', brokerGroup: 'A' },
  { code: 'ES', name: 'Spain', brokerGroup: 'A' },
  { code: 'ET', name: 'Ethiopia', brokerGroup: 'A' },
  { code: 'FI', name: 'Finland', brokerGroup: 'A' },
  { code: 'FJ', name: 'Fiji', brokerGroup: 'A' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', brokerGroup: 'A' },
  { code: 'FM', name: 'Micronesia', brokerGroup: 'A' },
  { code: 'FO', name: 'Faroe Islands', brokerGroup: 'A' },
  { code: 'FR', name: 'France', brokerGroup: 'A' },
  { code: 'GA', name: 'Gabon', brokerGroup: 'A' },
  { code: 'GD', name: 'Grenada', brokerGroup: 'A' },
  { code: 'GE', name: 'Georgia', brokerGroup: 'A' },
  { code: 'GF', name: 'French Guiana', brokerGroup: 'A' },
  { code: 'GG', name: 'Guernsey', brokerGroup: 'A' },
  { code: 'GH', name: 'Ghana', brokerGroup: 'A' },
  { code: 'GI', name: 'Gibraltar', brokerGroup: 'A' },
  { code: 'GL', name: 'Greenland', brokerGroup: 'A' },
  { code: 'GM', name: 'Gambia', brokerGroup: 'A' },
  { code: 'GN', name: 'Guinea', brokerGroup: 'A' },
  { code: 'GP', name: 'Guadeloupe', brokerGroup: 'A' },
  { code: 'GQ', name: 'Equatorial Guinea', brokerGroup: 'A' },
  { code: 'GR', name: 'Greece', brokerGroup: 'A' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', brokerGroup: 'A' },
  { code: 'GT', name: 'Guatemala', brokerGroup: 'A' },
  { code: 'GU', name: 'Guam', brokerGroup: 'A' },
  { code: 'GW', name: 'Guinea-Bissau', brokerGroup: 'A' },
  { code: 'GY', name: 'Guyana', brokerGroup: 'A' },
  { code: 'HK', name: 'Hong Kong', brokerGroup: 'A' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', brokerGroup: 'A' },
  { code: 'HN', name: 'Honduras', brokerGroup: 'A' },
  { code: 'HR', name: 'Croatia', brokerGroup: 'A' },
  { code: 'HT', name: 'Haiti', brokerGroup: 'A' },
  { code: 'HU', name: 'Hungary', brokerGroup: 'A' },
  { code: 'ID', name: 'Indonesia', brokerGroup: 'A' },
  { code: 'IE', name: 'Ireland', brokerGroup: 'A' },
  { code: 'IL', name: 'Israel', brokerGroup: 'A' },
  { code: 'IM', name: 'Isle of Man', brokerGroup: 'A' },
  { code: 'IN', name: 'India', brokerGroup: 'A' },
  { code: 'IO', name: 'British Indian Ocean Territory', brokerGroup: 'A' },
  { code: 'IQ', name: 'Iraq', brokerGroup: 'A' },
  { code: 'IR', name: 'Iran', brokerGroup: 'A' },
  { code: 'IS', name: 'Iceland', brokerGroup: 'A' },
  { code: 'IT', name: 'Italy', brokerGroup: 'A' },
  { code: 'JE', name: 'Jersey', brokerGroup: 'A' },
  { code: 'JM', name: 'Jamaica', brokerGroup: 'A' },
  { code: 'JO', name: 'Jordan', brokerGroup: 'A' },
  { code: 'JP', name: 'Japan', brokerGroup: 'A' },
  { code: 'KE', name: 'Kenya', brokerGroup: 'A' },
  { code: 'KG', name: 'Kyrgyzstan', brokerGroup: 'A' },
  { code: 'KH', name: 'Cambodia', brokerGroup: 'A' },
  { code: 'KI', name: 'Kiribati', brokerGroup: 'A' },
  { code: 'KM', name: 'Comoros', brokerGroup: 'A' },
  { code: 'KN', name: 'Saint Kitts and Nevis', brokerGroup: 'A' },
  { code: 'KP', name: 'Korea, Democratic People\'s Republic of', brokerGroup: 'A' },
  { code: 'KR', name: 'Korea, Republic of', brokerGroup: 'A' },
  { code: 'KW', name: 'Kuwait', brokerGroup: 'A' },
  { code: 'KY', name: 'Cayman Islands', brokerGroup: 'A' },
  { code: 'KZ', name: 'Kazakhstan', brokerGroup: 'A' },
  { code: 'LA', name: 'Lao People\'s Democratic Republic', brokerGroup: 'A' },
  { code: 'LB', name: 'Lebanon', brokerGroup: 'A' },
  { code: 'LC', name: 'Saint Lucia', brokerGroup: 'A' },
  { code: 'LI', name: 'Liechtenstein', brokerGroup: 'A' },
  { code: 'LK', name: 'Sri Lanka', brokerGroup: 'A' },
  { code: 'LR', name: 'Liberia', brokerGroup: 'A' },
  { code: 'LS', name: 'Lesotho', brokerGroup: 'A' },
  { code: 'LT', name: 'Lithuania', brokerGroup: 'A' },
  { code: 'LU', name: 'Luxembourg', brokerGroup: 'A' },
  { code: 'LV', name: 'Latvia', brokerGroup: 'A' },
  { code: 'LY', name: 'Libya', brokerGroup: 'A' },
  { code: 'MA', name: 'Morocco', brokerGroup: 'A' },
  { code: 'MC', name: 'Monaco', brokerGroup: 'A' },
  { code: 'MD', name: 'Moldova', brokerGroup: 'A' },
  { code: 'ME', name: 'Montenegro', brokerGroup: 'A' },
  { code: 'MF', name: 'Saint Martin (French part)', brokerGroup: 'A' },
  { code: 'MG', name: 'Madagascar', brokerGroup: 'A' },
  { code: 'MH', name: 'Marshall Islands', brokerGroup: 'A' },
  { code: 'MK', name: 'North Macedonia', brokerGroup: 'A' },
  { code: 'ML', name: 'Mali', brokerGroup: 'A' },
  { code: 'MM', name: 'Myanmar', brokerGroup: 'A' },
  { code: 'MN', name: 'Mongolia', brokerGroup: 'A' },
  { code: 'MO', name: 'Macao', brokerGroup: 'A' },
  { code: 'MP', name: 'Northern Mariana Islands', brokerGroup: 'A' },
  { code: 'MQ', name: 'Martinique', brokerGroup: 'A' },
  { code: 'MR', name: 'Mauritania', brokerGroup: 'A' },
  { code: 'MS', name: 'Montserrat', brokerGroup: 'A' },
  { code: 'MT', name: 'Malta', brokerGroup: 'A' },
  { code: 'MU', name: 'Mauritius', brokerGroup: 'A' },
  { code: 'MV', name: 'Maldives', brokerGroup: 'A' },
  { code: 'MW', name: 'Malawi', brokerGroup: 'A' },
  { code: 'MX', name: 'Mexico', brokerGroup: 'A' },
  { code: 'MY', name: 'Malaysia', brokerGroup: 'A' },
  { code: 'MZ', name: 'Mozambique', brokerGroup: 'A' },
  { code: 'NA', name: 'Namibia', brokerGroup: 'A' },
  { code: 'NC', name: 'New Caledonia', brokerGroup: 'A' },
  { code: 'NE', name: 'Niger', brokerGroup: 'A' },
  { code: 'NF', name: 'Norfolk Island', brokerGroup: 'A' },
  { code: 'NG', name: 'Nigeria', brokerGroup: 'A' },
  { code: 'NI', name: 'Nicaragua', brokerGroup: 'A' },
  { code: 'NL', name: 'Netherlands', brokerGroup: 'A' },
  { code: 'NO', name: 'Norway', brokerGroup: 'A' },
  { code: 'NP', name: 'Nepal', brokerGroup: 'A' },
  { code: 'NR', name: 'Nauru', brokerGroup: 'A' },
  { code: 'NU', name: 'Niue', brokerGroup: 'A' },
  { code: 'NZ', name: 'New Zealand', brokerGroup: 'A' },
  { code: 'OM', name: 'Oman', brokerGroup: 'A' },
  { code: 'PA', name: 'Panama', brokerGroup: 'A' },
  { code: 'PE', name: 'Peru', brokerGroup: 'A' },
  { code: 'PF', name: 'French Polynesia', brokerGroup: 'A' },
  { code: 'PG', name: 'Papua New Guinea', brokerGroup: 'A' },
  { code: 'PH', name: 'Philippines', brokerGroup: 'A' },
  { code: 'PK', name: 'Pakistan', brokerGroup: 'A' },
  { code: 'PL', name: 'Poland', brokerGroup: 'A' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', brokerGroup: 'A' },
  { code: 'PN', name: 'Pitcairn', brokerGroup: 'A' },
  { code: 'PR', name: 'Puerto Rico', brokerGroup: 'A' },
  { code: 'PS', name: 'Palestine, State of', brokerGroup: 'A' },
  { code: 'PT', name: 'Portugal', brokerGroup: 'A' },
  { code: 'PW', name: 'Palau', brokerGroup: 'A' },
  { code: 'PY', name: 'Paraguay', brokerGroup: 'A' },
  { code: 'QA', name: 'Qatar', brokerGroup: 'A' },
  { code: 'RE', name: 'Réunion', brokerGroup: 'A' },
  { code: 'RO', name: 'Romania', brokerGroup: 'A' },
  { code: 'RS', name: 'Serbia', brokerGroup: 'A' },
  { code: 'RU', name: 'Russian Federation', brokerGroup: 'A' },
  { code: 'RW', name: 'Rwanda', brokerGroup: 'A' },
  { code: 'SA', name: 'Saudi Arabia', brokerGroup: 'A' },
  { code: 'SB', name: 'Solomon Islands', brokerGroup: 'A' },
  { code: 'SC', name: 'Seychelles', brokerGroup: 'A' },
  { code: 'SD', name: 'Sudan', brokerGroup: 'A' },
  { code: 'SE', name: 'Sweden', brokerGroup: 'A' },
  { code: 'SG', name: 'Singapore', brokerGroup: 'A' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', brokerGroup: 'A' },
  { code: 'SI', name: 'Slovenia', brokerGroup: 'A' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', brokerGroup: 'A' },
  { code: 'SK', name: 'Slovakia', brokerGroup: 'A' },
  { code: 'SL', name: 'Sierra Leone', brokerGroup: 'A' },
  { code: 'SM', name: 'San Marino', brokerGroup: 'A' },
  { code: 'SN', name: 'Senegal', brokerGroup: 'A' },
  { code: 'SO', name: 'Somalia', brokerGroup: 'A' },
  { code: 'SR', name: 'Suriname', brokerGroup: 'A' },
  { code: 'SS', name: 'South Sudan', brokerGroup: 'A' },
  { code: 'ST', name: 'Sao Tome and Principe', brokerGroup: 'A' },
  { code: 'SV', name: 'El Salvador', brokerGroup: 'A' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', brokerGroup: 'A' },
  { code: 'SY', name: 'Syrian Arab Republic', brokerGroup: 'A' },
  { code: 'SZ', name: 'Eswatini', brokerGroup: 'A' },
  { code: 'TC', name: 'Turks and Caicos Islands', brokerGroup: 'A' },
  { code: 'TD', name: 'Chad', brokerGroup: 'A' },
  { code: 'TF', name: 'French Southern Territories', brokerGroup: 'A' },
  { code: 'TG', name: 'Togo', brokerGroup: 'A' },
  { code: 'TH', name: 'Thailand', brokerGroup: 'A' },
  { code: 'TJ', name: 'Tajikistan', brokerGroup: 'A' },
  { code: 'TK', name: 'Tokelau', brokerGroup: 'A' },
  { code: 'TL', name: 'Timor-Leste', brokerGroup: 'A' },
  { code: 'TM', name: 'Turkmenistan', brokerGroup: 'A' },
  { code: 'TN', name: 'Tunisia', brokerGroup: 'A' },
  { code: 'TO', name: 'Tonga', brokerGroup: 'A' },
  { code: 'TR', name: 'Turkey', brokerGroup: 'A' },
  { code: 'TT', name: 'Trinidad and Tobago', brokerGroup: 'A' },
  { code: 'TV', name: 'Tuvalu', brokerGroup: 'A' },
  { code: 'TW', name: 'Taiwan', brokerGroup: 'A' },
  { code: 'TZ', name: 'Tanzania', brokerGroup: 'A' },
  { code: 'UA', name: 'Ukraine', brokerGroup: 'A' },
  { code: 'UG', name: 'Uganda', brokerGroup: 'A' },
  { code: 'UM', name: 'United States Minor Outlying Islands', brokerGroup: 'A' },
  { code: 'UY', name: 'Uruguay', brokerGroup: 'A' },
  { code: 'UZ', name: 'Uzbekistan', brokerGroup: 'A' },
  { code: 'VA', name: 'Holy See (Vatican City State)', brokerGroup: 'A' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', brokerGroup: 'A' },
  { code: 'VE', name: 'Venezuela', brokerGroup: 'A' },
  { code: 'VG', name: 'Virgin Islands, British', brokerGroup: 'A' },
  { code: 'VI', name: 'Virgin Islands, U.S.', brokerGroup: 'A' },
  { code: 'VN', name: 'Viet Nam', brokerGroup: 'A' },
  { code: 'VU', name: 'Vanuatu', brokerGroup: 'A' },
  { code: 'WF', name: 'Wallis and Futuna', brokerGroup: 'A' },
  { code: 'WS', name: 'Samoa', brokerGroup: 'A' },
  { code: 'YE', name: 'Yemen', brokerGroup: 'A' },
  { code: 'YT', name: 'Mayotte', brokerGroup: 'A' },
  { code: 'ZA', name: 'South Africa', brokerGroup: 'A' },
  { code: 'ZM', name: 'Zambia', brokerGroup: 'A' },
  { code: 'ZW', name: 'Zimbabwe', brokerGroup: 'A' }
];

export const getBrokerUrl = (country: string): string => {
  const countryData = countries.find(c => c.code === country);
  const brokerGroup = countryData?.brokerGroup || 'A';
  
  switch (brokerGroup) {
    case 'B':
      return 'https://blackbull.com/en/live-account/?cmp=5p0z2d3q&refid=6436';
    case 'US':
      return 'coming-soon'; // Placeholder for future US broker
    case 'A':
    default:
      return 'https://ultgo.com/7f6bMz';
  }
};

export const detectCountryFromIP = async (): Promise<string | null> => {
  try {
    const response = await fetch('https://ipapi.co/json/');
    const data = await response.json();
    return data.country_code || null;
  } catch (error) {
    console.warn('Failed to detect country from IP:', error);
    return null;
  }
};