
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  Download, 
  Share2, 
  Copy, 
  TrendingUp, 
  TrendingDown,
  Eye,
  Crown
} from 'lucide-react';
import { SignalDNA } from '@/services/multiIntelligenceCore';
import { useToast } from '@/hooks/use-toast';
import html2canvas from 'html2canvas';

interface ShareableSignalCardProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  signal: SignalDNA | null;
}

const ShareableSignalCard: React.FC<ShareableSignalCardProps> = ({
  open,
  onOpenChange,
  signal
}) => {
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const { toast } = useToast();

  if (!signal) return null;

  const isLong = signal.type === 'BUY';
  
  const downloadAsImage = async () => {
    setIsGeneratingImage(true);
    try {
      const element = document.getElementById('shareable-signal-card');
      if (element) {
        const canvas = await html2canvas(element, {
          backgroundColor: '#0f0f23',
          scale: 2,
          logging: false,
        });
        
        const link = document.createElement('a');
        link.download = `aasakira-signal-${signal.symbol}-${Date.now()}.png`;
        link.href = canvas.toDataURL();
        link.click();
        
        toast({
          title: "Image Downloaded",
          description: "Your shareable signal card has been saved",
        });
      }
    } catch (error) {
      console.error('Failed to generate image:', error);
      toast({
        title: "Download Failed",
        description: "Unable to generate image. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingImage(false);
    }
  };

  const copySignalText = () => {
    const signalText = `
⛩️ AASAKIRA AI SIGNAL ⛩️

${signal.symbol} - ${signal.type}
Confidence: ${signal.confidence}%
Strategy: ${signal.framework}

Entry: ${Number(signal.structure.entry).toFixed(signal.symbol.includes('JPY') ? 3 : 5)}
Stop Loss: ${Number(signal.structure.stopLoss).toFixed(signal.symbol.includes('JPY') ? 3 : 5)}
Take Profit: ${Number(signal.structure.takeProfit).toFixed(signal.symbol.includes('JPY') ? 3 : 5)}
R:R Ratio: ${signal.structure.riskReward}:1

Generated by Aasakira AI - Premium Trading Intelligence
    `.trim();

    navigator.clipboard.writeText(signalText);
    toast({
      title: "Signal Copied",
      description: "Signal details copied to clipboard",
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl bg-slate-950 border-purple-500/30">
        <DialogHeader>
          <DialogTitle className="text-purple-400 text-xl flex items-center gap-2">
            <Share2 className="w-6 h-6" />
            Shareable Signal Card
          </DialogTitle>
        </DialogHeader>
        
        <div className="space-y-6">
          {/* Shareable Card Preview */}
          <div 
            id="shareable-signal-card"
            className="bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 border-2 border-purple-500/30 rounded-xl p-6 relative overflow-hidden"
          >
            {/* Background Effects */}
            <div className="absolute inset-0 bg-gradient-to-r from-purple-500/5 via-blue-500/5 to-cyan-500/5 animate-pulse" />
            
            {/* Header */}
            <div className="relative z-10 space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="text-2xl">⛩️</div>
                  <div>
                    <h3 className="text-white font-bold text-lg">AASAKIRA AI</h3>
                    <p className="text-purple-300 text-sm">Premium Trading Signal</p>
                  </div>
                </div>
                <Badge className="bg-gradient-to-r from-yellow-400 to-orange-400 text-black font-bold px-3 py-1 flex items-center gap-1">
                  <Crown className="w-3 h-3" />
                  CERTIFIED
                </Badge>
              </div>

              {/* Signal Details */}
              <Card className="bg-black/30 border border-gray-700/50">
                <CardContent className="p-4 space-y-4">
                  {/* Pair and Direction */}
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {isLong ? (
                        <TrendingUp className="w-8 h-8 text-green-400" />
                      ) : (
                        <TrendingDown className="w-8 h-8 text-red-400" />
                      )}
                      <div>
                        <div className="text-2xl font-bold text-white">{signal.symbol}</div>
                        <div className={`text-lg font-semibold ${isLong ? 'text-green-400' : 'text-red-400'}`}>
                          {signal.type}
                        </div>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="text-purple-300 text-sm">Confidence</div>
                      <div className="text-2xl font-bold text-purple-400">{signal.confidence}%</div>
                    </div>
                  </div>

                  {/* Trading Levels */}
                  <div className="grid grid-cols-3 gap-4 text-center">
                    <div className="bg-blue-500/10 border border-blue-500/20 rounded p-3">
                      <div className="text-blue-400 text-xs uppercase tracking-wide mb-1">Entry</div>
                      <div className="text-white font-bold font-mono text-sm">
                        {Number(signal.structure.entry).toFixed(signal.symbol.includes('JPY') ? 3 : 5)}
                      </div>
                    </div>
                    <div className="bg-red-500/10 border border-red-500/20 rounded p-3">
                      <div className="text-red-400 text-xs uppercase tracking-wide mb-1">Stop Loss</div>
                      <div className="text-white font-bold font-mono text-sm">
                        {Number(signal.structure.stopLoss).toFixed(signal.symbol.includes('JPY') ? 3 : 5)}
                      </div>
                    </div>
                    <div className="bg-green-500/10 border border-green-500/20 rounded p-3">
                      <div className="text-green-400 text-xs uppercase tracking-wide mb-1">Take Profit</div>
                      <div className="text-white font-bold font-mono text-sm">
                        {Number(signal.structure.takeProfit).toFixed(signal.symbol.includes('JPY') ? 3 : 5)}
                      </div>
                    </div>
                  </div>

                  {/* Additional Info */}
                  <div className="flex justify-between items-center pt-2 border-t border-gray-700/50">
                    <div className="text-sm text-gray-400">
                      Strategy: <span className="text-purple-300">{signal.framework}</span>
                    </div>
                    <div className="text-sm text-gray-400">
                      R:R: <span className="text-green-400">{signal.structure.riskReward}:1</span>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Footer */}
              <div className="text-center py-2">
                <div className="text-purple-400 font-semibold">Generated by Aasakira AI</div>
                <div className="text-gray-500 text-xs">Japanese Precision • AI Intelligence</div>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <Button
              onClick={downloadAsImage}
              disabled={isGeneratingImage}
              className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
            >
              <Download className="w-4 h-4 mr-2" />
              {isGeneratingImage ? 'Generating...' : 'Download Image'}
            </Button>
            
            <Button
              onClick={copySignalText}
              variant="outline"
              className="border-purple-500/30 text-purple-400 hover:bg-purple-500/20"
            >
              <Copy className="w-4 h-4 mr-2" />
              Copy Text
            </Button>
            
            <Button
              onClick={() => {
                toast({
                  title: "Share Feature",
                  description: "Social sharing coming soon!",
                });
              }}
              variant="outline"
              className="border-pink-500/30 text-pink-400 hover:bg-pink-500/20"
            >
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ShareableSignalCard;
