
import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog"
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Download, 
  Copy, 
  Share2, 
  TrendingUp, 
  TrendingDown,
  Target,
  Shield,
  Activity,
  Zap,
  RefreshCw
} from 'lucide-react';
import html2canvas from 'html2canvas';
import { SignalDNA } from '@/services/multiIntelligenceCore';
import { EnhancedSignal } from '@/services/enhancedSignalAnalyzer';
import { useToast } from '@/hooks/use-toast';

interface ShareableSignalCardProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  signal: SignalDNA | EnhancedSignal | any | null;
}

const ShareableSignalCard: React.FC<ShareableSignalCardProps> = ({ 
  open, 
  onOpenChange, 
  signal 
}) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  if (!signal) return null;

  const generateShareableCard = async () => {
    setIsGenerating(true);
    try {
      const cardElement = document.getElementById('shareable-signal-card');
      if (cardElement) {
        const canvas = await html2canvas(cardElement, {
          backgroundColor: '#0f172a',
          scale: 2,
          useCORS: true,
        });
        
        const link = document.createElement('a');
        const symbolOrPair = signal.symbol || signal.pair;
        link.download = `aasakira-signal-${symbolOrPair}-${Date.now()}.png`;
        link.href = canvas.toDataURL();
        link.click();
        
        toast({
          title: "Signal Image Downloaded",
          description: "Your signal image has been saved successfully!",
        });
      }
    } catch (error) {
      console.error('Failed to generate shareable card:', error);
      toast({
        title: "Download Failed",
        description: "Failed to generate signal image. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const copySignalText = () => {
    const symbolOrPair = signal.symbol || signal.pair;
    const tradeDirection = signal.type;
    const entry = signal.structure?.entry || signal.entry;
    const stopLoss = signal.structure?.stopLoss || signal.stopLoss;
    const takeProfit = signal.structure?.takeProfit || signal.takeProfit;
    
    const signalText = `🏛️ Aasakira AI Signal
    
📊 Pair: ${symbolOrPair}
🎯 Direction: ${tradeDirection}
💎 Confidence: ${signal.confidence}%

📈 Entry: ${Number(entry).toFixed(5)}
🛡️ Stop Loss: ${Number(stopLoss).toFixed(5)}
🎯 Take Profit: ${Number(takeProfit).toFixed(5)}

⚔️ AI Multi-Intelligence Analysis
Generated by Aasakira Trading Platform`;

    navigator.clipboard.writeText(signalText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    
    toast({
      title: "Signal Copied",
      description: "Signal details copied to clipboard!",
    });
  };

  const symbolOrPair = signal.symbol || signal.pair;
  const tradeDirection = signal.type;
  const entry = signal.structure?.entry || signal.entry;
  const stopLoss = signal.structure?.stopLoss || signal.stopLoss;
  const takeProfit = signal.structure?.takeProfit || signal.takeProfit;
  
  const riskReward = Math.abs(Number(takeProfit) - Number(entry)) / Math.abs(Number(entry) - Number(stopLoss));

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 border-purple-500/30">
        <DialogHeader>
          <DialogTitle className="text-white text-2xl font-bold flex items-center gap-3">
            <Share2 className="w-6 h-6 text-purple-400" />
            Share Professional Signal
          </DialogTitle>
          <DialogDescription className="text-gray-400">
            Generate a premium shareable image or copy formatted text
          </DialogDescription>
        </DialogHeader>

        <div 
          id="shareable-signal-card"
          className="relative bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 p-8 rounded-2xl border-2 border-purple-500/30 shadow-2xl"
        >
          {/* Background Pattern */}
          <div className="absolute inset-0 bg-gradient-to-r from-purple-500/5 via-blue-500/5 to-cyan-500/5 rounded-2xl" />
          
          {/* Header */}
          <div className="relative z-10 text-center mb-8">
            <div className="flex items-center justify-center gap-3 mb-4">
              <div className="w-12 h-12 bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-xl flex items-center justify-center border border-purple-500/30">
                ⛩️
              </div>
              <div>
                <h2 className="text-3xl font-bold text-white">Aasakira AI Signal</h2>
                <p className="text-purple-400 font-medium">Institutional Trading Intelligence</p>
              </div>
            </div>
          </div>

          {/* Signal Details */}
          <div className="relative z-10 space-y-6">
            {/* Main Signal Info */}
            <div className="flex items-center justify-between bg-gradient-to-r from-blue-500/10 to-purple-500/10 rounded-xl p-6 border border-blue-500/20">
              <div className="flex items-center gap-4">
                <div className={`w-16 h-16 rounded-xl flex items-center justify-center ${
                  tradeDirection === 'BUY' ? 'bg-green-500/20 border border-green-500/30' : 'bg-red-500/20 border border-red-500/30'
                }`}>
                  {tradeDirection === 'BUY' ? (
                    <TrendingUp className="w-8 h-8 text-green-400" />
                  ) : (
                    <TrendingDown className="w-8 h-8 text-red-400" />
                  )}
                </div>
                <div>
                  <h3 className="text-3xl font-bold text-white">{symbolOrPair}</h3>
                  <Badge className={`text-lg px-4 py-1 font-bold ${
                    tradeDirection === 'BUY' ? 'bg-green-500/20 text-green-400' : 'bg-red-500/20 text-red-400'
                  } border-0`}>
                    {tradeDirection}
                  </Badge>
                </div>
              </div>
              <div className="text-right">
                <div className="text-4xl font-bold text-purple-400 mb-2">
                  {signal.confidence}%
                </div>
                <Badge className="bg-purple-500/20 text-purple-400 border-purple-500/30 text-sm px-3 py-1">
                  AI CONFIDENCE
                </Badge>
              </div>
            </div>

            {/* Trading Levels */}
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-blue-500/10 border border-blue-500/30 rounded-xl p-4 text-center">
                <div className="flex items-center justify-center gap-2 mb-3">
                  <Target className="w-5 h-5 text-blue-400" />
                  <span className="text-blue-400 font-semibold">ENTRY</span>
                </div>
                <div className="text-2xl font-mono font-bold text-white">
                  {Number(entry).toFixed(5)}
                </div>
              </div>
              <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 text-center">
                <div className="flex items-center justify-center gap-2 mb-3">
                  <Shield className="w-5 h-5 text-red-400" />
                  <span className="text-red-400 font-semibold">STOP</span>
                </div>
                <div className="text-2xl font-mono font-bold text-white">
                  {Number(stopLoss).toFixed(5)}
                </div>
              </div>
              <div className="bg-green-500/10 border border-green-500/30 rounded-xl p-4 text-center">
                <div className="flex items-center justify-center gap-2 mb-3">
                  <Zap className="w-5 h-5 text-green-400" />
                  <span className="text-green-400 font-semibold">TARGET</span>
                </div>
                <div className="text-2xl font-mono font-bold text-white">
                  {Number(takeProfit).toFixed(5)}
                </div>
              </div>
            </div>

            {/* Risk Reward & Strategy */}
            <div className="flex items-center justify-between bg-gradient-to-r from-purple-500/10 to-pink-500/10 rounded-xl p-4 border border-purple-500/20">
              <div className="flex items-center gap-3">
                <Activity className="w-6 h-6 text-purple-400" />
                <div>
                  <span className="text-purple-400 font-semibold">Risk:Reward</span>
                  <div className="text-2xl font-bold text-white">{riskReward.toFixed(1)}:1</div>
                </div>
              </div>
              <div className="text-right">
                <span className="text-gray-400 text-sm">Strategy</span>
                <div className="text-purple-400 font-bold">AI Multi-Intelligence</div>
              </div>
            </div>

            {/* Footer */}
            <div className="text-center pt-4 border-t border-gray-700/50">
              <p className="text-gray-400 text-sm">
                Generated by <span className="text-purple-400 font-semibold">Aasakira Trading Platform</span>
              </p>
              <p className="text-gray-500 text-xs mt-1">
                {new Date().toLocaleString()}
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="grid grid-cols-2 gap-4 mt-6">
          <Button
            onClick={generateShareableCard}
            disabled={isGenerating}
            className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-bold py-3"
          >
            {isGenerating ? (
              <>
                <RefreshCw className="w-5 h-5 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Download className="w-5 h-5 mr-2" />
                Download Image
              </>
            )}
          </Button>
          
          <Button
            onClick={copySignalText}
            variant="outline"
            className="border-blue-500/30 text-blue-400 hover:bg-blue-500/20 font-bold py-3"
          >
            {copied ? (
              <>
                <Zap className="w-5 h-5 mr-2 text-green-400" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-5 h-5 mr-2" />
                Copy Text
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ShareableSignalCard;
