-- Create news_events table for storing economic calendar and news data
CREATE TABLE IF NOT EXISTS public.news_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT,
  title TEXT,
  country TEXT,
  impact TEXT,
  date TIMESTAMPTZ,
  actual TEXT,
  forecast TEXT,
  previous TEXT,
  source TEXT DEFAULT 'FCS',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for fast date queries
CREATE INDEX IF NOT EXISTS idx_news_events_date ON public.news_events (date);

-- Enable RLS
ALTER TABLE public.news_events ENABLE ROW LEVEL SECURITY;

-- Create policies for news events
CREATE POLICY "News events are viewable by everyone" 
ON public.news_events 
FOR SELECT 
USING (true);

CREATE POLICY "Service role can manage news events" 
ON public.news_events 
FOR ALL 
USING (true);